"""change date_read to string

Revision ID: a1da3641ebc6
Revises: 9adf0478a78f
Create Date: 2026-06-09 20:31:28.532993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1da3641ebc6'
down_revision = '9adf0478a78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('date_read',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('date_read',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
